###
# @name Obtain key
POST http://keycloak.szut.dev/auth/realms/szut/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=employee-management-service&username=user&password=test

### /projects
# @name Test with valid body data

POST localhost:8089/v1/projects/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "description": "Hallo ich bin ein Projekt!",
  "cid": 4,
  "employees": [
    1
  ],
  "qualifications": [
    1, 2
  ],
  "customerEmployeeName": "Kevin James",
  "comment": "Ich bin eine Kommentarziel lelele",
  "startDate": "2022-12-09T18:19:26.492745400",
  "estimatedEndDate": "2022-12-09T18:19:26.492745400",
  "endDate": "2022-12-09T18:19:26.492745400"
}

###
# @name Test with invalid body data

POST localhost:8089/v1/projects/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "description": "Hallo ich bin ein Projekt!",
  "eid": null,
  "cid": 4,
  "customerEmployeeName": null,
  "comment": "Ich bin eine Kommentarziel lelele",
  "startDate": "2022-12-09T18:19:26.492745400",
  "estimatedEndDate": "2022-12-09T18:19:26.492745400",
  "endDate": "2022-12-09T18:19:26.492745400"
}

###
# @name GetAllProjectsTest
GET localhost:8089/v1/projects/
Authorization: Bearer {{access_token}}
Content-Type: application/json

###
# @name GetOneProjectTest
GET localhost:8089/v1/projects/1
Authorization: Bearer {{access_token}}
Content-Type: application/json


### /projects/{projectId}
# @name UpdateProjectTest

PUT localhost:8089/v1/projects/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "description": "Neue Projektbeschreibung33",
  "cid": 6,
  "customerEmployeeName": "Neuer Mitarbeitername",
  "comment": "Aktualisierter Kommentar",
  "startDate": "2022-12-09T18:19:26.492745400",
  "estimatedEndDate": "2022-12-10T19:19:26.492745400",
  "endDate": "2022-12-09T18:19:26.492745400"
}

### /projects/{projectId}/addEmployee/{employeeId}
# @name AddEmployee

POST localhost:8089/v1/projects/1/addEmployee/5
Authorization: Bearer {{access_token}}
Content-Type: application/json

### /projects/{projectId}
# @name DeleteProjectTest
DELETE localhost:8089/v1/projects/3
Authorization: Bearer {{access_token}}
Content-Type: application/json

### https://employee.szut.dev/qualifications
# @name GetAllQualifications
GET https://employee.szut.dev/qualifications
Authorization: Bearer {{access_token}}
Content-Type: application/json


### https://employee.szut.dev/qualifications
# @name AddNewQualification
POST https://employee.szut.dev/qualifications
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "skill": "Springboot"
}